
Vagrant.configure("2") do |config|
  config.vm.box = "las/bullseye64"

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end
  
  config.vm.define "Manager" do |machine|
    machine.vm.hostname = "Manager"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
  end

  config.vm.define "Workstation" do |machine|
    machine.vm.hostname = "Workstation"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
  end
end
