- hosts: router1
  become: true
  roles:
    - common
    - routers_2_setup_L
    - syslog_setup
    - add_chron_job
    - snmp_manager
  tasks:
    - name: copy alert.sh
      ansible.builtin.copy:
        src: alert.sh
        dest: /usr/bin/alert.sh
        mode: 0755
- hosts: router2
  become: true
  roles:
    - common
    - routers_2_setup_R
    - syslog_setup
- hosts: server2router
  become: true
  roles:
    - common
    - servers
- hosts: client2router
  become: true
  tasks:
    - name: copy lastactive.sh
      ansible.builtin.copy:
        src: lastactive.sh
        dest: /usr/bin/lastactive.sh
        mode: 0755
  roles:
    - common
    - clients
    - snmp_agent
